import Link from "next/link";
import Nav from "../../components/Nav";
import CheckoutButton from "../../components/CheckoutButton";

export default function Revender(){return <main><Nav/><div className="container">
<section className="hero"><div><span className="eyebrow">PLANO REVENDEDOR • DIZECODE PARA NEGÓCIOS</span><h1>Venda mais do que o produto. Venda também a experiência.</h1><p className="lead">Inclua um QR dinâmico em canecas, camisetas, quadros, cartões, brindes, embalagens e outros produtos. Seu cliente recebe o produto físico e uma experiência digital que pode continuar sendo atualizada.</p><div className="resellerHeroPrice"><small>Plano Revendedor a partir de</small><strong>R$ 89,90 <span>/mês</span></strong><p>Até 100 QRs ativos para uso comercial e revenda.</p></div><div className="actions"><CheckoutButton product="reseller" label="Assinar plano Revendedor" featured={true}/><a href="#como-funciona" className="button secondary">Ver como funciona</a></div><p className="planClarifier">Este é o plano para quem quer vender DizeCode aos próprios clientes. Para uso próprio, veja os <Link href="/planos">planos DizeCode</Link>.</p></div><div className="heroCard"><span className="eyebrow">EXEMPLO DE POTENCIAL DE REVENDA</span><h2 style={{marginTop:18}}>100 clientes × R$ 19,90</h2><div className="bigRevenue">R$ 1.990</div><p className="muted">de receita bruta adicional no exemplo. Você define quanto cobrar do seu cliente pela experiência.</p></div></section>
<section className="section" id="como-funciona"><h2 className="sectionTitle">Como funciona para o revendedor</h2><div className="grid3"><div className="card"><h2>01</h2><h3>Ofereça</h3><p>Apresente a experiência digital como um adicional ao produto que você já vende.</p></div><div className="card"><h2>02</h2><h3>Crie</h3><p>Adicione o conteúdo do cliente e gere o QR dinâmico pelo seu painel.</p></div><div className="card"><h2>03</h2><h3>Entregue e cobre</h3><p>Baixe o QR, aplique na arte ou produto e defina sua própria margem de venda.</p></div></div></section>
<section className="section businessBand"><div><span className="eyebrow">PLANO REVENDEDOR</span><h2>R$ 89,90/mês</h2><p className="lead">Até 100 QRs ativos, uso comercial e revenda, painel de clientes, QR pronto para impressão, páginas sem marca DizeCode e estatísticas.</p><small>Não é uma cobrança adicional aos planos de uso próprio. É uma modalidade específica para revendedores.</small></div><CheckoutButton product="reseller" label="Começar como Revendedor" featured={true}/></section>
<section className="section"><h2 className="sectionTitle">Para quem este plano foi feito?</h2><div className="useGrid"><div className="useCard"><h3>Personalizados</h3><p>Canecas, camisetas, quadros, chaveiros, placas e lembranças.</p></div><div className="useCard"><h3>Gráficas</h3><p>Convites, cartões, impressos, embalagens e brindes corporativos.</p></div><div className="useCard"><h3>Agências</h3><p>Campanhas, ativações, lançamentos e experiências phygital.</p></div><div className="useCard"><h3>Eventos</h3><p>Casamentos, festas, formaturas, feiras e ações promocionais.</p></div><div className="useCard"><h3>Fotógrafos</h3><p>Álbuns e impressões que abrem vídeos, bastidores e galerias.</p></div><div className="useCard"><h3>Empresas</h3><p>Pós-venda, treinamento, instruções, fidelização e campanhas.</p></div></div></section>
<section className="resellerFinalCta"><span className="eyebrow">PRONTO PARA OFERECER DIZECODE?</span><h2>Comece com até 100 QRs ativos.</h2><p>Assine o Plano Revendedor e transforme produtos físicos em uma nova oportunidade de receita.</p><CheckoutButton product="reseller" label="Assinar por R$ 89,90/mês" featured={true}/><Link href="/planos" className="textLink">Não quero revender — ver planos para uso próprio →</Link></section>
</div></main>}
