import Link from "next/link";
import Nav from "../../components/Nav";
import CheckoutButton from "../../components/CheckoutButton";

export default function Revender(){return <main><Nav/><div className="container">
<section className="hero"><div><span className="eyebrow">PLANO REVENDEDOR • DIZECODE PARA NEGÓCIOS</span><h1>Venda mais do que o produto. Venda também a experiência.</h1><p className="lead">Inclua um QR dinâmico em canecas, camisetas, quadros, cartões, brindes, embalagens e outros produtos. Seu cliente recebe o produto físico e uma experiência digital que pode continuar sendo atualizada.</p><div className="resellerHeroPrice"><small>Preço de lançamento</small><strong>R$ 89,90 <span>/mês</span></strong><p>Até 100 QRs ativos para uso comercial e revenda.</p></div><div className="actions"><CheckoutButton product="reseller" label="Assinar plano Revendedor" featured={true}/><a href="#como-funciona" className="button secondary">Ver como funciona</a></div><p className="planClarifier">Você paga a DizeCode pela assinatura e cobra do seu cliente o valor que decidir. Os QRs incluídos na franquia do Revendedor não exigem a compra adicional da Experiência+ de R$ 9,90.</p></div><div className="heroCard"><span className="eyebrow">EXEMPLO DE POTENCIAL DE REVENDA</span><h2 style={{marginTop:18}}>100 clientes × R$ 19,90</h2><div className="bigRevenue">R$ 1.990</div><p className="muted">de receita bruta adicional no exemplo. Você define quanto cobrar do seu cliente pela experiência.</p></div></section>
<section className="resellerPromise"><span className="eyebrow">SEGURANÇA PARA QUEM JÁ RECEBEU O PRODUTO</span><h2>O QR impresso não deixa de funcionar porque você cancelou o plano.</h2><p>Experiências já publicadas continuam acessíveis para o cliente final em modo de leitura. Se a assinatura for cancelada ou ficar inativa, novas criações e alterações ficam bloqueadas. Ao reativar o plano, você volta a criar e editar normalmente.</p><div className="resellerPromiseGrid"><div><strong>QR já publicado</strong><span>Continua acessível.</span></div><div><strong>Novos QRs</strong><span>Exigem plano ativo.</span></div><div><strong>Edição do conteúdo</strong><span>Exige plano ativo.</span></div></div></section>
<section className="section" id="como-funciona"><h2 className="sectionTitle">Como funciona para o revendedor</h2><div className="grid3"><div className="card"><h2>01</h2><h3>Você oferece</h3><p>Apresente a experiência digital como um adicional ao produto que você já vende.</p></div><div className="card"><h2>02</h2><h3>Você cria</h3><p>Use sua franquia de até 100 QRs ativos. Não há cobrança de R$ 9,90 por cada QR incluído no plano.</p></div><div className="card"><h2>03</h2><h3>Você entrega e cobra</h3><p>Baixe o QR, aplique no produto e defina sua própria margem. A relação comercial com o cliente é sua.</p></div></div></section>
<section className="section businessBand"><div><span className="eyebrow">PLANO REVENDEDOR</span><h2>R$ 89,90/mês</h2><p className="lead">Até 100 QRs ativos, uso comercial e revenda, painel de clientes, QR pronto para impressão, páginas sem marca DizeCode e estatísticas.</p><small>A assinatura é paga pelo revendedor. Seus clientes finais não precisam contratar um plano DizeCode para visualizar as experiências que você entregar.</small></div><CheckoutButton product="reseller" label="Começar como Revendedor" featured={true}/></section>
<section className="section"><h2 className="sectionTitle">Perguntas importantes antes de vender</h2><div className="faqList"><details open><summary>Se eu cancelar o plano, os QRs que já vendi param de funcionar?</summary><p>Não. Experiências já publicadas continuam acessíveis em modo de leitura. O plano ativo é necessário para criar novos QRs e editar experiências existentes.</p></details><details><summary>Meu cliente precisa pagar R$ 9,90 pela Experiência+?</summary><p>Não para os QRs criados dentro da franquia do Plano Revendedor. Você paga a assinatura mensal e decide quanto cobrar do seu cliente pelo adicional digital.</p></details><details><summary>Quem recebe o pagamento do meu cliente?</summary><p>Você. A venda do produto e o valor cobrado pela experiência são definidos e recebidos pelo seu negócio. Sua cobrança da DizeCode é a assinatura do Plano Revendedor.</p></details><details><summary>Meu cliente precisa instalar aplicativo?</summary><p>Não. Ele escaneia o QR com a câmera do celular e abre a experiência no navegador.</p></details></div></section>
<section className="section"><h2 className="sectionTitle">Para quem este plano foi feito?</h2><div className="useGrid"><div className="useCard"><h3>Personalizados</h3><p>Canecas, camisetas, quadros, chaveiros, placas e lembranças.</p></div><div className="useCard"><h3>Gráficas</h3><p>Convites, cartões, impressos, embalagens e brindes corporativos.</p></div><div className="useCard"><h3>Agências</h3><p>Campanhas, ativações, lançamentos e experiências phygital.</p></div><div className="useCard"><h3>Eventos</h3><p>Casamentos, festas, formaturas, feiras e ações promocionais.</p></div><div className="useCard"><h3>Fotógrafos</h3><p>Álbuns e impressões que abrem vídeos, bastidores e galerias.</p></div><div className="useCard"><h3>Empresas</h3><p>Pós-venda, treinamento, instruções, fidelização e campanhas.</p></div></div></section>
<section className="resellerFinalCta"><span className="eyebrow">PREÇO DE LANÇAMENTO</span><h2>Comece com até 100 QRs ativos.</h2><p>R$ 89,90/mês. Você vende a experiência pelo preço que escolher e os QRs já entregues continuam acessíveis mesmo se futuramente cancelar o plano.</p><CheckoutButton product="reseller" label="Assinar por R$ 89,90/mês" featured={true}/><Link href="/planos" className="textLink">Não quero revender — ver planos para uso próprio →</Link></section>
</div></main>}
