import { createHmac, timingSafeEqual } from "crypto";
import { NextRequest, NextResponse } from "next/server";
const PRICES:Record<string,number>={experience:9.9,pro:29.9,reseller:89.9,business:199};const PLAN:Record<string,string>={pro:"pro",reseller:"reseller",business:"business"};
function parseRef(ref?:string|null){const m=/^(?:dizecode|memora):(experience|pro|reseller|business):([0-9a-f-]{36})$/i.exec(ref||"");return m?{product:m[1].toLowerCase(),userId:m[2].toLowerCase()}:null}
function validSignature(req:NextRequest,dataId:string){const secret=process.env.MERCADO_PAGO_WEBHOOK_SECRET;const signature=req.headers.get("x-signature");const requestId=req.headers.get("x-request-id");if(!secret||!signature||!requestId||!dataId)return false;const parts=Object.fromEntries(signature.split(",").map(part=>{const[k,...v]=part.trim().split("=");return[k,v.join("=")]}));const ts=parts.ts,v1=parts.v1;if(!ts||!v1)return false;const manifest=`id:${dataId.toLowerCase()};request-id:${requestId};ts:${ts};`;const expected=createHmac("sha256",secret).update(manifest).digest("hex");try{const a=Buffer.from(expected,"hex"),b=Buffer.from(v1,"hex");return a.length===b.length&&timingSafeEqual(a,b)}catch{return false}}
async function mpGet(path:string){const token=process.env.MERCADO_PAGO_ACCESS_TOKEN;if(!token)throw new Error("Mercado Pago não configurado");const r=await fetch(`https://api.mercadopago.com${path}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(r.status===404)return null;if(!r.ok)throw new Error(`Mercado Pago ${r.status}`);return r.json()}
async function supabase(path:string,init:RequestInit={}){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase admin não configurado");return fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal",...(init.headers||{})}})}
async function activate(userId:string,product:string,providerId:string,periodEnd?:string|null){if(product==="experience"){const read=await supabase(`account_plans?user_id=eq.${userId}&select=user_id,plan,premium_credits`);if(!read.ok)throw new Error("Falha ao ler créditos");const rows=await read.json();const credits=Number(rows?.[0]?.premium_credits||0)+1;const write=await supabase("account_plans?on_conflict=user_id",{method:"POST",body:JSON.stringify({user_id:userId,plan:rows?.[0]?.plan||"free",status:"active",premium_credits:credits,updated_at:new Date().toISOString()})});if(!write.ok)throw new Error("Falha ao liberar crédito")}else{const write=await supabase("account_plans?on_conflict=user_id",{method:"POST",body:JSON.stringify({user_id:userId,plan:PLAN[product],status:"active",current_period_end:periodEnd||null,updated_at:new Date().toISOString()})});if(!write.ok)throw new Error("Falha ao liberar plano")}console.info("payment_activated",{userId,product,providerId})}
export async function POST(req:NextRequest){try{const body=await req.json().catch(()=>({}));const type=String(body?.type||body?.topic||req.nextUrl.searchParams.get("type")||req.nextUrl.searchParams.get("topic")||"");const id=String(body?.data?.id||body?.id||req.nextUrl.searchParams.get("data.id")||req.nextUrl.searchParams.get("id")||"");if(!id)return NextResponse.json({ok:true});if(!validSignature(req,id))return NextResponse.json({error:"Assinatura inválida."},{status:401});if(type==="payment"){const p=await mpGet(`/v1/payments/${encodeURIComponent(id)}`);if(!p)return NextResponse.json({ok:true});const ref=parseRef(p.external_reference);if(!ref||p.status!=="approved")return NextResponse.json({ok:true});if(Math.abs(Number(p.transaction_amount)-PRICES[ref.product])>.001||String(p.currency_id)!=="BRL")return NextResponse.json({ok:true});if(ref.product==="experience")await activate(ref.userId,ref.product,String(p.id));return NextResponse.json({ok:true})}if(type==="subscription_preapproval"||type==="preapproval"){const s=await mpGet(`/preapproval/${encodeURIComponent(id)}`);if(!s)return NextResponse.json({ok:true});const ref=parseRef(s.external_reference);if(!ref||ref.product==="experience")return NextResponse.json({ok:true});const amount=Number(s.auto_recurring?.transaction_amount);if(s.status==="authorized"&&Math.abs(amount-PRICES[ref.product])<=.001&&String(s.auto_recurring?.currency_id)==="BRL")await activate(ref.userId,ref.product,String(s.id),s.next_payment_date||null);else if(["cancelled","paused"].includes(String(s.status))){const r=await supabase(`account_plans?user_id=eq.${ref.userId}`,{method:"PATCH",body:JSON.stringify({status:"canceled",updated_at:new Date().toISOString()})});if(!r.ok)throw new Error("Falha ao cancelar plano")}return NextResponse.json({ok:true})}return NextResponse.json({ok:true})}catch(e:any){console.error("mercadopago_webhook_error",e?.message||e);return NextResponse.json({ok:false},{status:500})}}
