import Link from "next/link";
import Nav from "../components/Nav";
import HeroExperience from "../components/HeroExperience";
import HomeVideo from "../components/HomeVideo";

export default function Home() {
  return <main><Nav/><div className="container">
    <section className="hero"><div><span className="eyebrow">DizeCode • QR dinâmico + experiência digital</span><h1>Todo produto tem algo a dizer.</h1><p className="lead">Conecte o mundo físico ao digital com um QR que pode guardar histórias, vender, ensinar, surpreender e continuar mudando depois de impresso. Use em presentes, produtos, embalagens, campanhas, eventos, cartões, vitrines e muito mais.</p><div className="actions"><Link href="/login?next=/criar" className="button">Criar meu primeiro QR grátis</Link><Link href="/revender" className="button secondary">Quero usar no meu negócio</Link></div><div className="techPoints"><span>QR dinâmico</span><span>Conteúdo editável</span><span>Vídeo, foto e áudio</span></div></div><div className="heroVisual"><HeroExperience/></div></section>
    <section className="videoShowcase" id="video"><div><span className="eyebrow">Veja a DizeCode em ação</span><h2>Do QR para uma experiência em segundos.</h2><p className="lead">Mostre um tutorial, uma demonstração ou uma campanha em vídeo. Quando estiver logado, use o botão abaixo do player para trocar o conteúdo.</p><div className="actions"><Link href="/login?next=/criar" className="button">Criar experiência</Link></div></div><HomeVideo/></section>
    <section className="section"><span className="eyebrow">feito para pessoas e negócios</span><h2 className="sectionTitle">Onde a DizeCode pode estar</h2><div className="useGrid"><div className="useCard"><span>🎁</span><h3>Presentes</h3><p>Fotos, vídeos, áudios e mensagens em presentes personalizados.</p></div><div className="useCard"><span>📦</span><h3>Produtos</h3><p>Transforme embalagens, etiquetas e personalizados em experiências.</p></div><div className="useCard"><span>📣</span><h3>Marketing</h3><p>Campanhas atualizáveis, promoções, lançamentos e captação de leads.</p></div><div className="useCard"><span>🎉</span><h3>Eventos</h3><p>Convites, casamentos, aniversários, formaturas e lembranças.</p></div><div className="useCard"><span>🏪</span><h3>Comércio</h3><p>Cardápios, vitrines, instruções, pós-venda e fidelização.</p></div><div className="useCard"><span>💼</span><h3>Revenda</h3><p>Venda experiências digitais junto aos produtos que você já produz.</p></div></div></section>
    <section className="section businessBand"><div><span className="eyebrow">nova fonte de receita</span><h2>Você personaliza produtos? Venda também a experiência.</h2><p className="lead">Gráficas, lojas de presentes, fotógrafos, agências e personalizadores podem criar DizeCodes para seus clientes, aplicar sua própria margem e administrar tudo em um único painel.</p></div><Link href="/revender" className="button">Conhecer plano Revendedor</Link></section>
    <section className="section centerCta"><h2>Dê voz ao que é físico.</h2><p className="lead">Crie uma experiência gratuitamente e descubra como a DizeCode conecta seu presente, produto ou campanha ao digital.</p><div className="actions"><Link href="/login?next=/criar" className="button">Começar grátis</Link><Link href="/planos" className="button secondary">Ver planos</Link></div></section>
  </div></main>;
}
