import Link from "next/link";
import Nav from "../../components/Nav";

const plans = [
  {name:"Free",price:"R$ 0",desc:"Para descobrir a Memora",items:["1 QR ativo","Texto ou 1 mídia","Página pública","QR permanente","Marca Memora"],cta:"Começar grátis",href:"/login?next=/criar"},
  {name:"Memória+",price:"R$ 19,90",suffix:"por experiência",desc:"Para presentes e momentos especiais",items:["1 experiência premium","Foto + vídeo + áudio + texto","Edite sem trocar o QR","Temas premium","Sem marca Memora"],cta:"Criar experiência",href:"/login?next=/criar",featured:true},
  {name:"Pro",price:"R$ 39,90",suffix:"/mês",desc:"Para criadores e uso frequente",items:["Até 30 QRs ativos","Edição ilimitada","Estatísticas de acessos","Mais armazenamento","Organização em painel"],cta:"Quero ser Pro",href:"/login"},
  {name:"Revendedor",price:"R$ 89,90",suffix:"/mês",desc:"Para lucrar com seus clientes",items:["Até 100 QRs ativos","Uso comercial e revenda","Painel de clientes","Sem marca Memora","QR pronto para impressão","Relatórios de acessos"],cta:"Quero revender",href:"/revender"},
  {name:"Business",price:"R$ 199",suffix:"/mês",desc:"Para operações em escala",items:["Até 500 QRs ativos","Equipe e permissões","Identidade da empresa","Integrações e automações","Campanhas em escala","Suporte prioritário"],cta:"Falar sobre Business",href:"/revender"}
];

export default function Planos(){return <main><Nav/><div className="container"><section className="pricingHero"><span className="eyebrow">planos que crescem com você</span><h1>Comece grátis. Pague quando a experiência crescer.</h1><p className="lead">Para uma homenagem, dezenas de clientes ou uma campanha inteira. Escolha o modelo que combina com o seu uso.</p></section><section className="pricingGrid">{plans.map(p=><article className={`priceCard ${p.featured?"featured":""}`} key={p.name}>{p.featured&&<div className="popular">MAIS ESCOLHIDO</div>}<h3>{p.name}</h3><p className="muted">{p.desc}</p><div className="price">{p.price}<small>{p.suffix||""}</small></div><ul>{p.items.map(i=><li key={i}>✓ {i}</li>)}</ul><Link href={p.href} className={`button ${p.featured?"":"secondary"}`}>{p.cta}</Link></article>)}</section><section className="section centerCta"><h2>Vai colocar QR em produtos para vender?</h2><p className="lead">O plano Revendedor foi pensado para você transformar a Memora em uma nova linha de receita.</p><Link href="/revender" className="button">Conhecer revenda</Link></section></div></main>}
