"use client";
import {useState} from "react";
import Link from "next/link";
import Nav from "../../components/Nav";
import CheckoutButton from "../../components/CheckoutButton";

const paid={pro:{name:"Pro",monthly:29.9,annual:299,desc:"Para quem cria e gerencia seus próprios QRs",items:["Até 30 QRs ativos","Edição ilimitada","Estatísticas de acessos","Mais armazenamento","Organização em painel"]},business:{name:"Business",monthly:199,annual:1990,desc:"Para empresas e operações em escala",items:["Até 500 QRs ativos","Equipe e permissões","Identidade da empresa","Integrações e automações","Campanhas em escala","Suporte prioritário"]}} as const;
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export default function Planos(){const[cycle,setCycle]=useState<"monthly"|"annual">("monthly");return <main><Nav/><div className="container">
<section className="pricingHero"><div className="launchBanner"><strong>PREÇOS DE LANÇAMENTO</strong><span>Condições especiais para os primeiros usuários da DizeCode.</span></div><span className="eyebrow">PLANOS PARA USAR A DIZECODE</span><h1>Escolha como você quer usar seus QRs.</h1><p className="lead">Pague mensalmente ou escolha o anual e economize o equivalente a aproximadamente 2 meses.</p><div className="billingToggle"><button className={cycle==="monthly"?"active":""} onClick={()=>setCycle("monthly")}>Mensal</button><button className={cycle==="annual"?"active":""} onClick={()=>setCycle("annual")}>Anual <strong>2 meses grátis</strong></button></div></section>
<section className="pricingGrid standardPlans"><article className="priceCard"><h3>Free</h3><p className="muted">Para conhecer a DizeCode e criar seu primeiro QR</p><div className="price">R$ 0</div><ul>{["1 QR ativo","Texto ou 1 mídia","Página pública","QR permanente","Marca DizeCode"].map(i=><li key={i}>✓ {i}</li>)}</ul><Link href="/login?next=/criar" className="button secondary">Começar grátis</Link></article><article className="priceCard featured"><div className="popular">MAIS ESCOLHIDO</div><h3>Experiência+</h3><p className="muted">Para presentes e momentos especiais, sem assinatura</p><div className="price">R$ 9,90<small> pagamento único</small></div><ul>{["1 experiência premium","Foto + vídeo + áudio + texto","Edite sem trocar o QR","Temas premium","Sem marca DizeCode"].map(i=><li key={i}>✓ {i}</li>)}</ul><CheckoutButton product="experience" label="Comprar Experiência+" featured/></article>{Object.entries(paid).map(([key,p])=>{const annual=cycle==="annual";const price=annual?p.annual:p.monthly;const monthlyEquivalent=p.annual/12;return <article className="priceCard" key={key}><h3>{p.name}</h3><p className="muted">{p.desc}</p><div className="price">{money(price)}<small>{annual?"/ano":"/mês"}</small></div>{annual&&<div className="annualSaving"><strong>{money(monthlyEquivalent)}/mês</strong><span>equivalente • 2 meses grátis</span></div>}<ul>{p.items.map(i=><li key={i}>✓ {i}</li>)}</ul><CheckoutButton product={key as "pro"|"business"} billingCycle={cycle} label={annual?`Assinar ${p.name} anual`:`Assinar ${p.name}`}/></article>})}</section>
<section className="resellerPlanBand"><div className="resellerPlanCopy"><span className="eyebrow">QUERO VENDER DIZECODE AOS MEUS CLIENTES</span><h2>Plano Revendedor</h2><p>Você paga a DizeCode e define livremente quanto cobrar do seu cliente. Os QRs incluídos na franquia não têm cobrança avulsa de R$ 9,90.</p><div className="resellerMiniBenefits"><span>✓ Até 100 QRs ativos</span><span>✓ Uso comercial e revenda</span><span>✓ Painel de clientes</span><span>✓ Sem marca DizeCode</span></div><div className="resellerSafety"><strong>QR já entregue não desaparece se você cancelar.</strong><span>Experiências publicadas continuam acessíveis em modo de leitura; novas criações e edições exigem plano ativo.</span></div></div><div className="resellerPlanPrice"><small>{cycle==="annual"?"Anual • 2 meses grátis":"Preço de lançamento"}</small><strong>{cycle==="annual"?"R$ 899":"R$ 89,90"}</strong><span>{cycle==="annual"?"/ano":"/mês"}</span>{cycle==="annual"&&<small>equivale a R$ 74,92/mês</small>}<CheckoutButton product="reseller" billingCycle={cycle} label={cycle==="annual"?"Assinar Revendedor anual":"Assinar plano Revendedor"} featured/><Link href="/revender" className="textLink">Entender como funciona a revenda →</Link></div></section>
<section className="planHelp"><h2>Pagamento simples</h2><div><p><strong>Mensal</strong><br/>Libera 30 dias de acesso ao plano.</p><p><strong>Anual</strong><br/>Um pagamento libera 365 dias e oferece aproximadamente 2 meses grátis.</p><p><strong>Forma de pagamento</strong><br/>Após escolher o plano, você segue para o Mercado Pago e escolhe uma das opções disponibilizadas no checkout.</p></div></section>
</div></main>}
