import Link from "next/link";
import Nav from "../../components/Nav";
import CheckoutButton from "../../components/CheckoutButton";

const plans=[
{name:"Free",price:"R$ 0",desc:"Para conhecer a DizeCode e criar seu primeiro QR",items:["1 QR ativo","Texto ou 1 mídia","Página pública","QR permanente","Marca DizeCode"],cta:"Começar grátis",href:"/login?next=/criar"},
{name:"Experiência+",price:"R$ 9,90",suffix:"pagamento único por experiência",desc:"Para presentes e momentos especiais, sem assinatura mensal",items:["1 experiência premium","Foto + vídeo + áudio + texto","Edite sem trocar o QR","Temas premium","Sem marca DizeCode","Pagamento feito pelo dono da conta DizeCode"],cta:"Comprar Experiência+",product:"experience",featured:true},
{name:"Pro",price:"R$ 29,90",suffix:"/mês",desc:"Para quem cria e gerencia seus próprios QRs",items:["Até 30 QRs ativos","Edição ilimitada","Estatísticas de acessos","Mais armazenamento","Organização em painel"],cta:"Assinar Pro",product:"pro"},
{name:"Business",price:"R$ 199",suffix:"/mês",desc:"Para empresas e operações em escala",items:["Até 500 QRs ativos","Equipe e permissões","Identidade da empresa","Integrações e automações","Campanhas em escala","Suporte prioritário"],cta:"Assinar Business",product:"business"}] as const;

export default function Planos(){return <main><Nav/><div className="container">
<section className="pricingHero"><div className="launchBanner"><strong>PREÇOS DE LANÇAMENTO</strong><span>Condições especiais para os primeiros usuários da DizeCode.</span></div><span className="eyebrow">PLANOS PARA USAR A DIZECODE</span><h1>Escolha como você quer usar seus QRs.</h1><p className="lead">Estes planos são para criar experiências para você, sua marca ou sua empresa. Se você quer vender DizeCode aos seus próprios clientes, use o Plano Revendedor.</p></section>
<section className="pricingGrid standardPlans">{plans.map(p=><article className={`priceCard ${"featured" in p&&p.featured?"featured":""}`} key={p.name}>{"featured" in p&&p.featured&&<div className="popular">MAIS ESCOLHIDO</div>}<h3>{p.name}</h3><p className="muted">{p.desc}</p><div className="price">{p.price}<small>{"suffix" in p?p.suffix:""}</small></div><ul>{p.items.map(i=><li key={i}>✓ {i}</li>)}</ul>{"product" in p?<CheckoutButton product={p.product} label={p.cta} featured={"featured" in p&&!!p.featured}/>:<Link href={p.href} className="button secondary">{p.cta}</Link>}</article>)}</section>
<section className="resellerPlanBand"><div className="resellerPlanCopy"><span className="eyebrow">QUERO VENDER DIZECODE AOS MEUS CLIENTES</span><h2>Plano Revendedor</h2><p>Você paga a assinatura da DizeCode e define livremente quanto cobrar do seu cliente. O cliente final não precisa pagar R$ 9,90 à DizeCode para cada QR incluído na sua franquia.</p><div className="resellerMiniBenefits"><span>✓ Até 100 QRs ativos incluídos</span><span>✓ Sem cobrança Experiência+ por QR da franquia</span><span>✓ Uso comercial e revenda</span><span>✓ Painel de clientes</span><span>✓ Sem marca DizeCode</span></div><div className="resellerSafety"><strong>QR já entregue não desaparece se você cancelar.</strong><span>Experiências já publicadas continuam acessíveis em modo de leitura. O cancelamento bloqueia novas criações e edições até a reativação do plano.</span></div></div><div className="resellerPlanPrice"><small>Preço de lançamento</small><strong>R$ 89,90</strong><span>/mês</span><CheckoutButton product="reseller" label="Assinar plano Revendedor" featured={true}/><Link href="/revender" className="textLink">Entender como funciona a revenda →</Link></div></section>
<section className="planHelp"><h2>Qual caminho é o seu?</h2><div><p><strong>Quero uma experiência avulsa</strong><br/>Experiência+ custa R$ 9,90 uma única vez por experiência. Não é mensal.</p><p><strong>Quero usar DizeCode nos meus próprios projetos</strong><br/>Escolha Free, Experiência+, Pro ou Business acima.</p><p><strong>Quero cobrar dos meus clientes pela experiência digital</strong><br/>No Revendedor, você paga R$ 89,90/mês, recebe até 100 QRs ativos e define sua própria margem.</p></div></section>
</div></main>}
